import React from "react";
import Navbar from "../../components/Navbar";
import Head from "next/head";
import Image from "next/image";

const RecipeDetails = () => {
  return (
    <>
      <Head>
        <title>Foodie Recipes | Fried Chicken</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className=" grid grid-cols-2 h-screen p-4 ">
        <div className=" h-full w-full relative p-4">
          <Image src="/chicken.jpg" fill className=" object-cover rounded-md" />
        </div>
        <div className=" grid grid-cols-3 pl-2 pr-2">
          <span className="flex justify-center items-center cursor-pointer h-10 border-b-4 bg-violet-300 border-violet-500 ">
            Ingredients
          </span>
          <span className="flex justify-center items-center cursor-pointer h-10">
            Directions
          </span>
          <span className="flex justify-center items-center cursor-pointer h-10">
            Notes
          </span>
        </div>
      </main>
    </>
  );
};

export default RecipeDetails;
