import React from "react";
import Head from "next/head";
import Navbar from "../../components/Navbar";

const NewRecipe = () => {
  return (
    <>
      <Head>
        <title>Foodie Recipes | Add New Recipe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
};

export default NewRecipe;
